package controller;

import dao.SupplierDAO;
import model.Supplier;
import java.util.List;

public class SupplierController {

    private SupplierDAO dao = new SupplierDAO();

    // Get all suppliers
    public List<Supplier> getSuppliers() {
        return dao.getAllSuppliers();
    }

    // Add a new supplier
    public void addSupplier(String name, String phone, String email, String address) {
        Supplier s = new Supplier(0, name, phone, email, address); // ID will be auto-generated by DB
        dao.addSupplier(s);
    }

    // Get supplier by ID
    public Supplier getSupplier(int supplier_id) {
        return dao.getSupplierById(supplier_id);
    }
}